### ISSUE TITLE
parker p5js目录里的folder名字取的太混乱了

### ISSUE THREAD

**Issue by Sichengthebest** [HDCodePractice/SwiftPracticeResult#1694]
- [ ] 改名字

**Comment by Sichengthebest** [comment]
classdrawings 和 mydrawings 有什么区别？

**Comment by hdcola** [comment]
> classdrawings 和 mydrawings 有什么区别？
他喜欢将一个混乱的目录呈现给他人，这个不强制要求，对你们也一样。
这个目录是你们将来的一个名片，需要自己维护的。看看 @ParkerXChen  自己是否想更新了

**Comment by Sichengthebest** [comment]
- [ ] 改名字

**Comment by Sichengthebest** [comment]
耶！
github太牛了
