### ISSUE TITLE
改进一下宝石家场吧

### ISSUE THREAD

**Issue by hdcola** [HDCodePractice/SwiftPracticeResult#504]
Sichengthebest/Learn to Code 1/宝石农场/main.swift

学了一段时间了，再看看这个代码，有没有感觉可以写的更精简一些，同时，有没有发现取完最后一颗宝石后还多走了好几步？

**Comment by Sichengthebest** [comment]
OK

**Comment by Sichengthebest** [comment]
不是宝石农场吗……

**Comment by hdcola** [comment]
> 不是宝石农场吗……

是啊

**Comment by hdcola** [comment]
发现我又写错字了
